server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8080
          predicates:
            - Path=/account/**
        - id: loan-service
          uri: http://localhost:8081
          predicates:
            - Path=/loan/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
